# Generated by Django 5.2 on 2026-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_department_institute_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='e.g., CI02', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'department')},
        ),
    ]
