# Generated by Django 5.2 on 2026-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_subject_code_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tutorial_hours_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
