# Generated by Django 5.2 on 2026-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_subject_tutorial_hours_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='current_session',
            field=models.CharField(choices=[('ODD', 'Odd (Jul-Dec)'), ('EVEN', 'Even (Jan-Jun)')], default='ODD', max_length=10),
        ),
    ]
