# Generated by Django 5.2 on 2026-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_department_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='excluded_semesters',
            field=models.CharField(blank=True, default='', help_text='Comma separated list of semester numbers to ignore', max_length=50),
        ),
    ]
