# Generated by Django 5.2 on 2026-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_department_excluded_semesters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='tutorial_hours',
            field=models.IntegerField(default=0),
        ),
    ]
