# Generated by Django 5.2 on 2026-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_subjectallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='preferred_subjects',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_faculty', to='timetable.subject'),
        ),
    ]
